### PR TITLE
Better Builds, Extension Safe and Swift Checking

### PR DESCRIPTION
**Pull request by RPangrle**
Pushing some improvements that have been sitting on my dev box for a little while.

* An improved build script.
There's a single build script written in Python now that builds all of our libraries and frameworks and test apps. It also spits out better output and a summary at the end so it should be easier to run a validation build on your dev box before check in.

* Sample Swift App
Added a sample swift app that consumes are framework to make sure that build doesn't get broken and provide a simple bit of sample code on how to use the API in Swift.

* Cleaned up Extension Build Paths
Separated out the "core" libraries from targets that copy headers so they don't conflict with framework includes, however if you build both in the same dev environment it still will break things as the underlying issue is a bug with how Xcode prioritizes header include paths vs framework include paths.

* Test Share Extension added to the Test App
Doesn't test much except the build right now, but is marginally useful for future test code.

### CODE REVIEW

**Comment by jasoncoolmax** [comment]
:shipit:

**Comment by RPangrle** [comment]
Fixed #694 deployment target set to 8.0 across the board now.

**Comment by RPangrle** [comment]
Mitigates #693

**Comment by RPangrle** [comment]
Fixed #97

**Pull request merged**
