### PR TITLE
Fix interface builder error in Xcode 9 beta 4

### PR DESCRIPTION
**Pull request by chaseholland**
Revving version to 1.2.9.1 and fixing interface builder error in xcode 9 beta 4 for version 1.2.9.

### CODE REVIEW

**Comment by chaseholland** [comment]
I'm not sure what the best branch to open this CR into is (I forked from tag v1.2.9). This looked like the most appropriate on the list.

**Comment by oldalton** [comment]
@chaseholland There's a merge conflict, can you resolve it? I can then approve this PR.

**Comment by chaseholland** [comment]
Sure thing!

**Comment by chaseholland** [comment]
Conflicts should be resolved. Please double check my work.

**Comment by oldalton** [comment]
@chaseholland Thanks for fixing conflicts. One last thing: can you also update .travis.yml file and switch it to "xcode8.3", so the build stops failing. It looks like it's not compatible with Xcode 7 anymore. Thanks!

**Comment by chaseholland** [comment]
Done! Sorry that took me so long.

**Comment by ramonpoca** [comment]
Will need a 1.2.9.1 tag as well and push the 1.2.9.1 podspec to Cocoapods.

**Pull request merged**
