### PR TITLE
Pluggable Auth Handlers

### PR DESCRIPTION
**Pull request by RPangrle**
Architect NSURL auth handlers so we can plug in different classes for different auth types.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398%23issuecomment-150066913%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398%23issuecomment-150067794%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398%23issuecomment-150313242%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398%23issuecomment-150066913%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Are%20you%20doing%20this%20to%20allow%20for%20client%20TLS%20via%20Safari%20/%20System%20Web%20View%3F%22%2C%20%22created_at%22%3A%20%222015-10-22T00%3A58%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4307330%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RandalliLama%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes.%20This%20bit%20is%20so%20we%20can%20intercept%20cert%20auth%20requests%2C%20the%20meat%20of%20the%20implementation%20will%20be%20elsewhere.%22%2C%20%22created_at%22%3A%20%222015-10-22T01%3A01%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7004783%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RPangrle%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-22T18%3A23%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4307330%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RandalliLama%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/RandalliLama%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4307330%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/RandalliLama'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398#issuecomment-150066913'>General Comment</a></b>
- <a href='https://github.com/RandalliLama'></a> Are you doing this to allow for client TLS via Safari / System Web View?
- <a href='https://github.com/RPangrle'></a> Yes. This bit is so we can intercept cert auth requests, the meat of the implementation will be elsewhere.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/398?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/398?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/398?approve=0'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/398'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by RandalliLama** [comment]
Are you doing this to allow for client TLS via Safari / System Web View?

**Comment by RPangrle** [comment]
Yes. This bit is so we can intercept cert auth requests, the meat of the implementation will be elsewhere.

**Comment by RandalliLama** [comment]
:shipit:

**Pull request merged**
