### PR TITLE
Osxuniversal leak check

### PR DESCRIPTION
**Pull request by kpanwar**
Fixed the retain and release for CFTypes.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%23issuecomment-92424167%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%23issuecomment-92424620%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%23issuecomment-92424687%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%23issuecomment-93118880%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%23issuecomment-92424167%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20Kanishk%2C%5Cr%5CnHow%20can%20I%20download%20source%20code%20for%20this%20pull%20request%2C%20locally%3F%5Cr%5Cn%5Cr%5CnOn%20Apr%2013%2C%202015%2C%20at%209%3A41%20AM%2C%20Kanishk%20Panwar%20%3Cnotifications%40github.com%3Cmailto%3Anotifications%40github.com%3E%3E%20wrote%3A%5Cr%5Cn%5Cr%5Cn%5Cr%5CnFixed%20the%20retain%20and%20release%20for%20CFTypes.%5Cr%5Cn%5Cr%5Cn________________________________%5Cr%5CnYou%20can%20view%2C%20comment%20on%2C%20or%20merge%20this%20pull%20request%20online%20at%3A%5Cr%5Cn%5Cr%5Cn%20%20https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%5Cr%5Cn%5Cr%5CnCommit%20Summary%5Cr%5Cn%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23260%20from%20AzureAD/OSXUniversal-dev%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23269%20from%20AzureAD/OSXUniversal-dev%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23271%20from%20AzureAD/OSXUniversal-dev%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23277%20from%20AzureAD/OSXUniversal-dev%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23285%20from%20AzureAD/OSXUniversal-dev%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23289%20from%20AzureAD/OSXUniversal-dev%5Cr%5Cn%20%20%2A%20%20%20fix%20retain/release%5Cr%5Cn%20%20%2A%20%20%20Merge%20pull%20request%20%23294%20from%20AzureAD/OSXUniversal%5Cr%5Cn%5Cr%5CnFile%20Changes%5Cr%5Cn%5Cr%5Cn%20%20%2A%20%20%20M%20ADALiOS/ADALiOS/RegistrationInformation.m%3Chttps%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files%23diff-0%3E%20%285%29%5Cr%5Cn%20%20%2A%20%20%20M%20ADALiOS/ADALiOS/WorkPlaceJoinUtil.m%3Chttps%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files%23diff-1%3E%20%283%29%5Cr%5Cn%20%20%2A%20%20%20M%20Samples/MyTestiOSApp/MyTestiOSApp.xcodeproj/project.pbxproj%3Chttps%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files%23diff-2%3E%20%285%29%5Cr%5Cn%20%20%2A%20%20%20M%20Samples/MyTestiOSApp/MyTestiOSApp/MyTestiOSApp.entitlements%3Chttps%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files%23diff-3%3E%20%288%29%5Cr%5Cn%5Cr%5CnPatch%20Links%3A%5Cr%5Cn%5Cr%5Cn%20%20%2A%20%20%20https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295.patch%5Cr%5Cn%20%20%2A%20%20%20https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295.diff%5Cr%5Cn%5Cr%5Cn%5Cu2014%5Cr%5CnReply%20to%20this%20email%20directly%20or%20view%20it%20on%20GitHub%3Chttps%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295%3E.%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-04-13T16%3A56%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10979061%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ranyelhousieny%22%7D%7D%2C%20%7B%22body%22%3A%20%22you%20can%20clone%20the%20repository%20using%20git%20clone%20%3Cbranch_name%3E.%20then%20switch%20to%20the%20branch%20using%20%5C%22git%20checkout%20osxuniversal-leak-check%5C%22%22%2C%20%22created_at%22%3A%20%222015-04-13T16%3A58%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-04-13T16%3A59%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22Could%20you%20please%20move%20the%20CFRelease%20next%20to%20the%20corresponding%20assignment%20above%20so%20that%20it%20is%20clear%20that%20you%20are%20retaining%20where%20it%20is%20being%20assigned%2C%20as%20follows%3F%5Cr%5Cn%20if%28self%29%5Cr%5Cn%20%20%20%20%7B%5Cr%5Cn%20%20%20%20%20%20%20%20_identity%20%3D%20identity%3B%5Cr%5Cn%20%20%20%20%20%20%20%20CFRetain%28_identity%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20_userPrincipalName%20%3D%20SAFE_ARC_RETAIN%28userPrincipalName%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20_certificate%20%3D%20certificate%3B%5Cr%5Cn%20%20%20%20%20%20%20%20CFRetain%28_certificate%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20_certificateSubject%20%3D%20SAFE_ARC_RETAIN%28certificateSubject%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20_certificateData%20%3D%20SAFE_ARC_RETAIN%28certificateData%29%3B%5Cr%5Cn%20%20%20%20%20%20%20%20_privateKey%20%3D%20privateKey%3B%5Cr%5Cn%20%20%20%20%20%20%20%20CFRetain%28_privateKey%29%3B%5Cr%5Cn%5Cr%5Cn%5Cr%5CnThanks%22%2C%20%22created_at%22%3A%20%222015-04-15T00%3A03%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10979061%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ranyelhousieny%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295#issuecomment-92424167'>General Comment</a></b>
- <a href='https://github.com/ranyelhousieny'></a> Hi Kanishk,
How can I download source code for this pull request, locally?
On Apr 13, 2015, at 9:41 AM, Kanishk Panwar <notifications@github.com<mailto:notifications@github.com>> wrote:
Fixed the retain and release for CFTypes.
________________________________
You can view, comment on, or merge this pull request online at:
https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295
Commit Summary
*   Merge pull request #260 from AzureAD/OSXUniversal-dev
*   Merge pull request #269 from AzureAD/OSXUniversal-dev
*   Merge pull request #271 from AzureAD/OSXUniversal-dev
*   Merge pull request #277 from AzureAD/OSXUniversal-dev
*   Merge pull request #285 from AzureAD/OSXUniversal-dev
*   Merge pull request #289 from AzureAD/OSXUniversal-dev
*   fix retain/release
*   Merge pull request #294 from AzureAD/OSXUniversal
File Changes
*   M ADALiOS/ADALiOS/RegistrationInformation.m<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-0> (5)
*   M ADALiOS/ADALiOS/WorkPlaceJoinUtil.m<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-1> (3)
*   M Samples/MyTestiOSApp/MyTestiOSApp.xcodeproj/project.pbxproj<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-2> (5)
*   M Samples/MyTestiOSApp/MyTestiOSApp/MyTestiOSApp.entitlements<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-3> (8)
Patch Links:
*   https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295.patch
*   https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295.diff
—
Reply to this email directly or view it on GitHub<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295>.
- <a href='https://github.com/kpanwar'></a> you can clone the repository using git clone <branch_name>. then switch to the branch using "git checkout osxuniversal-leak-check"
- <a href='https://github.com/kpanwar'></a> :+1:
- <a href='https://github.com/ranyelhousieny'></a> Could you please move the CFRelease next to the corresponding assignment above so that it is clear that you are retaining where it is being assigned, as follows?
if(self)
{
_identity = identity;
CFRetain(_identity);
_userPrincipalName = SAFE_ARC_RETAIN(userPrincipalName);
_certificate = certificate;
CFRetain(_certificate);
_certificateSubject = SAFE_ARC_RETAIN(certificateSubject);
_certificateData = SAFE_ARC_RETAIN(certificateData);
_privateKey = privateKey;
CFRetain(_privateKey);
Thanks

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/295?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/295?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by ranyelhousieny** [comment]
Hi Kanishk,
How can I download source code for this pull request, locally?

On Apr 13, 2015, at 9:41 AM, Kanishk Panwar <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed the retain and release for CFTypes.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295

Commit Summary

  *   Merge pull request #260 from AzureAD/OSXUniversal-dev
  *   Merge pull request #269 from AzureAD/OSXUniversal-dev
  *   Merge pull request #271 from AzureAD/OSXUniversal-dev
  *   Merge pull request #277 from AzureAD/OSXUniversal-dev
  *   Merge pull request #285 from AzureAD/OSXUniversal-dev
  *   Merge pull request #289 from AzureAD/OSXUniversal-dev
  *   fix retain/release
  *   Merge pull request #294 from AzureAD/OSXUniversal

File Changes

  *   M ADALiOS/ADALiOS/RegistrationInformation.m<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-0> (5)
  *   M ADALiOS/ADALiOS/WorkPlaceJoinUtil.m<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-1> (3)
  *   M Samples/MyTestiOSApp/MyTestiOSApp.xcodeproj/project.pbxproj<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-2> (5)
  *   M Samples/MyTestiOSApp/MyTestiOSApp/MyTestiOSApp.entitlements<https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295/files#diff-3> (8)

Patch Links:

  *   https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295.patch
  *   https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/295.diff

**Comment by kpanwar** [comment]
you can clone the repository using git clone <branch_name>. then switch to the branch using "git checkout osxuniversal-leak-check"

**Comment by kpanwar** [comment]
:+1:

**Comment by ranyelhousieny** [comment]
Could you please move the CFRelease next to the corresponding assignment above so that it is clear that you are retaining where it is being assigned, as follows?
 if(self)
    {
        _identity = identity;
        CFRetain(_identity);
        _userPrincipalName = SAFE_ARC_RETAIN(userPrincipalName);
        _certificate = certificate;
        CFRetain(_certificate);
        _certificateSubject = SAFE_ARC_RETAIN(certificateSubject);
        _certificateData = SAFE_ARC_RETAIN(certificateData);
        _privateKey = privateKey;
        CFRetain(_privateKey);


Thanks

**Pull request merged**
