### PR TITLE
update bundle name

### PR DESCRIPTION
**Pull request by kpanwar**
update bundle name - Issue#300
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301%23issuecomment-95711175%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301%23issuecomment-95714841%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301%23issuecomment-95715436%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301%23issuecomment-95750557%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301%23issuecomment-95711175%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Fix%20for%20https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/issues/300%22%2C%20%22created_at%22%3A%20%222015-04-23T20%3A30%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20also%20update%20the%20test%20app%20to%20use%20the%20bundle%20instead%20of%20the%20nibs%2C%20so%20that%20you%20can%20verify%20the%20fix%3F%22%2C%20%22created_at%22%3A%20%222015-04-23T20%3A49%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7786778%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/HiKumar-MS%22%7D%7D%2C%20%7B%22body%22%3A%20%22done%20%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-04-23T20%3A52%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-23T23%3A45%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7786778%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/HiKumar-MS%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/HiKumar-MS%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7786778%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/HiKumar-MS'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301#issuecomment-95711175'>General Comment</a></b>
- <a href='https://github.com/kpanwar'></a> Fix for https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/300
- <a href='https://github.com/HiKumar-MS'></a> Can you also update the test app to use the bundle instead of the nibs, so that you can verify the fix?
- <a href='https://github.com/kpanwar'></a> done :+1:

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/301?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/301?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/301?approve=0'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/301'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by kpanwar** [comment]
Fix for https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/300

**Comment by HiKumar-MS** [comment]
Can you also update the test app to use the bundle instead of the nibs, so that you can verify the fix?

**Comment by kpanwar** [comment]
:+1:

**Comment by HiKumar-MS** [comment]
:shipit:

**Pull request merged**
