### PR TITLE
fixed currentViewController method

### PR DESCRIPTION
**Pull request by novgo**
The rootViewController method does not always return the current viewController.
If the root view controller is already presenting a modal view controller its view is not even in the view hierarchy.

In ADAuthentication Broker this leads to an unhandled error when another modal view controller is currently presented.

    Attempt to present <UINavigationController: 0x17523ef0> on <UINavigationController: 0x1754a1f0> whose     view is not in the window hierarchy!
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243%23issuecomment-70400036%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243%23issuecomment-70471159%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243%23issuecomment-70552601%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243%23issuecomment-72168101%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243%23issuecomment-72762096%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243%23issuecomment-70400036%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40novgo%20%3A%20you%20changes%20are%20breaking%20the%20build.%20Can%20you%20please%20validate%20your%20changes%20against%20the%20test%20cases%20first%3F%22%2C%20%22created_at%22%3A%20%222015-01-18T08%3A12%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40kpanwar%20The%20tests%20for%20the%20current%20dev%20branch%20where%20already%20broken.%20The%20failing%20test%20%5C%22testRefreshingTokenWithServerErrors%3A%5C%22%20does%20not%20call%20any%20of%20the%20code%20i%20changed.%22%2C%20%22created_at%22%3A%20%222015-01-19T10%3A14%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8446811%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/novgo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40novgo%20-%20While%20I%20work%20on%20merging%20your%20changes%20can%20you%20please%20sign%20the%20CLA%20available%20at%20https%3A//cla.microsoft.com%3F%20Let%20me%20know%20when%20you%20are%20done.%22%2C%20%22created_at%22%3A%20%222015-01-19T20%3A07%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40kpanwar%20sorry%20it%20took%20some%20time%20to%20reach%20my%20boss%20but%20now%20we%20signed%20the%20CLA.%20So%20should%20i%20commit%20to%20the%20master%20branch%20and%20make%20a%20new%20pull%20request%3F%22%2C%20%22created_at%22%3A%20%222015-01-30T08%3A19%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8446811%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/novgo%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%2C%20please.%20I%20would%20take%20the%20pull%20request%20into%20MASTER.%20As%20soon%20as%20you%20are%20finished%2C%20I%20will%20release%201.2.0%20tag.%22%2C%20%22created_at%22%3A%20%222015-02-03T23%3A50%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5713915%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kpanwar%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243#issuecomment-70400036'>General Comment</a></b>
- <a href='https://github.com/kpanwar'></a> @novgo : you changes are breaking the build. Can you please validate your changes against the test cases first?
- <a href='https://github.com/novgo'></a> @kpanwar The tests for the current dev branch where already broken. The failing test "testRefreshingTokenWithServerErrors:" does not call any of the code i changed.
- <a href='https://github.com/kpanwar'></a> @novgo - While I work on merging your changes can you please sign the CLA available at https://cla.microsoft.com? Let me know when you are done.
- <a href='https://github.com/novgo'></a> @kpanwar sorry it took some time to reach my boss but now we signed the CLA. So should i commit to the master branch and make a new pull request?
- <a href='https://github.com/kpanwar'></a> Yes, please. I would take the pull request into MASTER. As soon as you are finished, I will release 1.2.0 tag.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/243?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-objc/pull/243?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/243'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by kpanwar** [comment]
@novgo : you changes are breaking the build. Can you please validate your changes against the test cases first?

**Comment by novgo** [comment]
@kpanwar The tests for the current dev branch where already broken. The failing test "testRefreshingTokenWithServerErrors:" does not call any of the code i changed.

**Comment by kpanwar** [comment]
@novgo - While I work on merging your changes can you please sign the CLA available at https://cla.microsoft.com? Let me know when you are done.

**Comment by novgo** [comment]
@kpanwar sorry it took some time to reach my boss but now we signed the CLA. So should i commit to the master branch and make a new pull request?

**Comment by kpanwar** [comment]
Yes, please. I would take the pull request into MASTER. As soon as you are finished, I will release 1.2.0 tag.

**Pull request closed without merging**
